apiVersion: v2
name: deployment
description: A Helm chart for application deployments
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - deployment
  - kubernetes
maintainers:
  - name: k3s-homelab
    email: admin@example.com

